In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "DataCoSupplyChainDataset.csv",
    encoding="latin1"
)

print("Dataset loaded successfully")
print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])

Dataset loaded successfully
Total rows: 180519
Total columns: 53

In [2]:
missing_audit = pd.DataFrame({
    "Missing Values Count": df.isnull().sum(),
    "Missing Values Percentage":
        (df.isnull().mean() * 100).round(2),
    "Non-Missing Values Count": df.notnull().sum()
})

missing_audit = missing_audit[
    missing_audit["Missing Values Count"] > 0
].sort_values("Missing Values Count", ascending=False)

display(missing_audit)

,Missing Values Count,Missing Values Percentage,Non-Missing Values Count
Product Description,180519,100.00,0
Order Zipcode,155679,86.24,24840
Customer Lname,8,0.00,180511
Customer Zipcode,3,0.00,180516

In [3]:
print("Exact duplicate rows:", df.duplicated().sum())

print(
    "Repeated Order ID entries:",
    df["Order Id"].duplicated().sum()
)

order_counts = df["Order Id"].value_counts()
repeated_ids = order_counts[order_counts > 1]

print("Unique Order IDs repeated:", len(repeated_ids))

Exact duplicate rows: 0
Repeated Order ID entries: 114767
Unique Order IDs repeated: 45902

In [4]:
# Check invalid or inconsistent values
print("Negative Sales:", (df["Sales"] < 0).sum())
print("Zero or negative Order Quantity:",
      (df["Order Item Quantity"] <= 0).sum())

# Check date validity
order_dates = pd.to_datetime(
    df["order date (DateOrders)"],
    errors="coerce"
)

shipping_dates = pd.to_datetime(
    df["shipping date (DateOrders)"],
    errors="coerce"
)

print("Invalid order dates:", order_dates.isna().sum())
print("Invalid shipping dates:", shipping_dates.isna().sum())
print("Shipping before order:",
      (shipping_dates < order_dates).sum())

Negative Sales: 0
Zero or negative Order Quantity: 0
Invalid order dates: 0
Invalid shipping dates: 0
Shipping before order: 0

In [5]:
audit_summary = pd.DataFrame({
    "Metric": [
        "Total Rows",
        "Total Columns",
        "Total Missing Values",
        "Columns with Missing Values",
        "Exact Duplicate Rows",
        "Repeated Order ID Entries",
        "Unique Order IDs Repeated"
    ],
    "Result": [
        len(df),
        len(df.columns),
        int(df.isnull().sum().sum()),
        int((df.isnull().sum() > 0).sum()),
        int(df.duplicated().sum()),
        int(df["Order Id"].duplicated().sum()),
        int((df["Order Id"].value_counts() > 1).sum())
    ]
})

display(audit_summary)

                        Metric  Result
0                   Total Rows  180519
1                Total Columns      53
2         Total Missing Values  336209
3  Columns with Missing Values       4
4         Exact Duplicate Rows       0
5    Repeated Order ID Entries  114767
6    Unique Order IDs Repeated   45902

In [11]:
import os

print("Current folder:", os.getcwd())

for filename in [
    "Final_Missing_Value_Audit.csv",
    "Final_Data_Quality_Summary.csv"
]:
    print(filename, "->", os.path.abspath(filename))
    print("Exists:", os.path.exists(filename))

Current folder: C:\Users\HP\Internship
Final_Missing_Value_Audit.csv -> C:\Users\HP\Internship\Final_Missing_Value_Audit.csv
Exists: True
Final_Data_Quality_Summary.csv -> C:\Users\HP\Internship\Final_Data_Quality_Summary.csv
Exists: True